# Generated by Django 4.1.7 on 2023-04-24 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_category_options_alter_product_options'),
        ('store', '0005_product_category'),
    ]

    operations = [
    ]
